### PR TITLE
stbt.Display: added clock on each frame's left top corner

### PR DESCRIPTION
**Pull request by Drachenfels**
While recording a video with this commit there will be visible clock
on left top corner. Clock displays time when given frame was
processed. In addition when calling a function 'press' we will draw not
only an information that button was pressed but as well time when it was
pressed. This should provide accurate information that will let us find
relation between actions registered in logs and what happened on screen.

### CODE REVIEW

**Comment by aiman** [comment]
Hi Dave. Now that stbt 0.21 is out, perhaps you can take a look at this again.

**Comment by szemate** [comment]
Hi, sorry for pushing this again, but basically this patch is now the only reason why we're maintaining a fork of stb-tester. If you are worried that it might clash with https://github.com/wmanley/stb-tester/commit/e1b69a2bbf796d3c73e8258438af1250901dd7bf, couldn't it go behind a command-line switch?

**Comment by drothlis** [comment]
Hi @szemate thanks for the reminder.

This needs rebasing onto master (it doesn't merge cleanly) and the test failures need to be fixed.

**Comment by drothlis** [comment]
Closed as a duplicate of #255.

**Pull request closed without merging**
